### ISSUE TITLE
Disallow adding non-factory constructors

### ISSUE THREAD

**Issue by chikamichi** [CodingSoot/modddels#6]
Hi,

I have [some code available on GitHub](https://github.com/kaibun/tmp-pub/tree/04de027cf47d7adb3983d54a09df7b1956fa9a88) showcasing a weird issue.

Context: refactoring a working app to leverage DDD, with proper [SoC](https://en.wikipedia.org/wiki/Separation_of_concerns) between:
- features (what the end-user _does_)
  - which leverage widgets (what the end-user _sees_ and can _interact with_)
    - which leverage widgets controllers (indirection sublayer in the Presentation layer)
      - which (in this POC) are Riverpod async providers for modddels (in the Domain layer), with eventually remote data being fetched through a DataMapper layer

---

I got a union of modddels ([source](https://github.com/kaibun/tmp-pub/blob/04de027cf47d7adb3983d54a09df7b1956fa9a88/lib/ddd/models/entities/map_layer/map_layer.dart)) named `MapLayer`, with three unioned "variants": `MapLayer.raster`, `MapLayer.vector` and `MapLayer.geojson`. I applied your insights from #4 and got it working… until I try to get a modddel instance.

On [this specific call](https://github.com/kaibun/tmp-pub/blob/04de027cf47d7adb3983d54a09df7b1956fa9a88/lib/ddd/features/Map/MapLayerController.dart#L71) I get the following exception: _UnsupportedError (Unsupported operation: It seems like you constructed your class using `MyClass._()`, or you tried to access an instance member from within the annotated class.)_

My understanding is that it would only ever be raised only if trying to call `MapLayer._()` or an instance method such as `map` on a raw `MapLayer` instance, but it’s not what I’m doing here: I’m instantiating through the factory `MapLayer.raster`.

What am I missing?

Thank you!

**Comment by CodingSoot** [comment]
Hi,

The problem is in your `Percentage` modddel :

```dart
class Percentage extends SingleValueObject<InvalidPercentage, ValidPercentage>
    with _$Percentage {
  Percentage._();

  factory Percentage(double value) {
    return _$Percentage._create(
      value: value,
    );
  }
  
  /// ⚠️ The problem is here
  Percentage.maxed() {
    Percentage(1.0);
  }

  // ...
}
```

Here, you're declaring a named constructor `Percentage.maxed`. Calling it is the same as calling `Percentage._()` : it creates a blank unusable instance of `Percentage`, and that's why the error is thrown. In the constructor body, you properly create a `Percentage` instance, but you don't use it.

What you want to achieve is not possible, as normally you would need to use a named factory constructor, something like this : 

```dart
factory Percentage.maxed() {
   return Percentage(1.0);
 }
```

However, named factory constructors are reserved for creating [union of modddels](https://docs.modddels.dev/union-of-modddels/union-of-modddels-overview). What I would suggest is to instead use a static method or getter : 

```dart
static Percentage maxed() => Percentage(1.0);
// or

static Percentage get maxed => Percentage(1.0);
```

I think I should completely disallow adding non-factory constructors to a modddel class, as I can't see any valid usecase for them.

**Comment by CodingSoot** [comment]
@chikamichi Let me know if this fixed your issue

**Comment by chikamichi** [comment]
Thank you very much! You were right.

I was in the process of uncovering the exact stacktrace for I had a feeling `MapLayer` was not the actual culprit… you saved me some time again ;)

> I think I should completely disallow adding non-factory constructors to a modddel class, as I can't see any valid usecase for them.

Agreed… until someone finds a legit use-case ;) Maybe just some warning/insight in the doc?

**Comment by CodingSoot** [comment]
> Agreed… until someone finds a legit use-case ;) Maybe just some warning/insight in the doc?

I've decided to completely disallow non-factory constructors, as they serve no practical purpose and could potentially confuse newcomers.
